apiVersion: v1
kind: Service
metadata:
  name: flask-calculator
spec:
  selector:
    app: flask-calculator
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
  type: NodePort
